In [1]:
# file "https://www.kaggle.com/settings"
#files.upload() #upload kaggle.json (Legacy API Credentials)

#!mkdir -p ~/.kaggle/

# Move the uploaded kaggle.json file to the .kaggle directory
#!mv kaggle.json ~/.kaggle/

# Set secure permissions for the API key file (read-only for owner)
#!chmod 600 ~/.kaggle/kaggle.json

# ! kaggle competitions download -c super-ai-engineer-ss-6-heart-disease-prediction

# Load the data from kaggle and upload here.
# !unzip aggle competitions download -c super-ai-engineer-ss-6-heart-disease-prediction.zip

In [2]:
import pandas as pd
import math

In [3]:
train_df = pd.read_csv("train.csv")
train_df.pop("ID")

train_df.head()

,History of HeartDisease or Attack,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Leisure Physical Activity,Heavy Alcohol Consumption,Health Care Coverage,Doctor Visit Cost Barrier,General Health,Difficulty Walking,Sex,Education Level,Income Level,Age,Vegetable or Fruit Intake (1+ per Day)
0,No,Yes,Yes,Yes,40.68,Yes,No,No,No,No,Yes,No,Very Poor,Yes,Female,High school graduate,"$15,000 to less than $20,000",64,Yes
1,No,No,No,No,24.36,Yes,No,No,Yes,No,No,Yes,Fair,No,Female,College graduate,"Less than $10,000",50,No
2,No,Yes,Yes,Yes,27.33,No,No,No,No,No,Yes,Yes,Very Poor,Yes,Female,High school graduate,"$75,000 or more",61,Yes
3,No,Yes,No,Yes,27.01,No,No,No,Yes,No,Yes,No,Good,No,Female,Some high school,"$35,000 to less than $50,000",74,Yes
4,NaN,Yes,Yes,Yes,34.56,Yes,No,No,Yes,No,Yes,Yes,Very Poor,Yes,Male,Some high school,"$15,000 to less than $20,000",98,Yes

In [4]:
train_df.shape

(223084, 19)

In [5]:
train_df.describe()

       Body Mass Index            Age
count    211302.000000  223084.000000
mean         28.189817      54.739717
std           6.688447      17.795140
min          11.210000      18.000000
25%          23.880000      42.000000
50%          27.070000      56.000000
75%          31.100000      67.000000
max          98.630000     100.000000

In [6]:
shape_Before_Clean = train_df.shape
train_df.shape

(223084, 19)

In [7]:
train_df.isnull().sum()

History of HeartDisease or Attack          1694
High Blood Pressure                           0
Told High Cholesterol                     32186
Cholesterol Checked                           0
Body Mass Index                           11782
Smoked 100+ Cigarettes                        1
Diagnosed Stroke                              0
Diagnosed Diabetes                            3
Leisure Physical Activity                     0
Heavy Alcohol Consumption                     0
Health Care Coverage                          0
Doctor Visit Cost Barrier                     1
General Health                                1
Difficulty Walking                            3
Sex                                           0
Education Level                               0
Income Level                                  0
Age                                           0
Vegetable or Fruit Intake (1+ per Day)        0
dtype: int64

In [8]:
# first version drop all missing Data
# drop all data that No hx of heart
train_df = train_df.dropna(subset=["History of HeartDisease or Attack"])
train_df = train_df.dropna(subset=["Told High Cholesterol"])
train_df = train_df.dropna(subset=["Body Mass Index"])
train_df = train_df.dropna(subset=["Diagnosed Diabetes"])
train_df = train_df.dropna(subset=["Doctor Visit Cost Barrier"])
train_df = train_df.dropna(subset=["Difficulty Walking"])
train_df = train_df.dropna(subset=["General Health"])

train_df.isnull().sum()

History of HeartDisease or Attack         0
High Blood Pressure                       0
Told High Cholesterol                     0
Cholesterol Checked                       0
Body Mass Index                           0
Smoked 100+ Cigarettes                    0
Diagnosed Stroke                          0
Diagnosed Diabetes                        0
Leisure Physical Activity                 0
Heavy Alcohol Consumption                 0
Health Care Coverage                      0
Doctor Visit Cost Barrier                 0
General Health                            0
Difficulty Walking                        0
Sex                                       0
Education Level                           0
Income Level                              0
Age                                       0
Vegetable or Fruit Intake (1+ per Day)    0
dtype: int64

In [9]:
train_df.shape

(179319, 19)

In [10]:
shape_After_Clean = train_df.shape
Data_Loss = round(abs((shape_Before_Clean[0] - shape_After_Clean[0])/shape_Before_Clean[0] * 100 ),2)
print("Data loss : "+str(Data_Loss)+" %")

Data loss : 19.62 %

In [11]:
train_df.head()

,History of HeartDisease or Attack,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Leisure Physical Activity,Heavy Alcohol Consumption,Health Care Coverage,Doctor Visit Cost Barrier,General Health,Difficulty Walking,Sex,Education Level,Income Level,Age,Vegetable or Fruit Intake (1+ per Day)
0,No,Yes,Yes,Yes,40.68,Yes,No,No,No,No,Yes,No,Very Poor,Yes,Female,High school graduate,"$15,000 to less than $20,000",64,Yes
1,No,No,No,No,24.36,Yes,No,No,Yes,No,No,Yes,Fair,No,Female,College graduate,"Less than $10,000",50,No
2,No,Yes,Yes,Yes,27.33,No,No,No,No,No,Yes,Yes,Very Poor,Yes,Female,High school graduate,"$75,000 or more",61,Yes
3,No,Yes,No,Yes,27.01,No,No,No,Yes,No,Yes,No,Good,No,Female,Some high school,"$35,000 to less than $50,000",74,Yes
5,No,Yes,Yes,Yes,25.11,Yes,No,No,Yes,No,Yes,No,Good,No,Male,College graduate,"$75,000 or more",67,Yes

In [12]:
train_df['General Health'].unique()

array(['Very Poor', 'Fair', 'Good', 'Poor', 'Excellent'], dtype=object)

In [13]:
# due to General Health may ordinal data change in to int

train_df['General Health'] = train_df['General Health'].mask(train_df['General Health'] == 'Very Poor', -2 )

train_df['General Health'] = train_df['General Health'].mask(train_df['General Health'] == 'Poor', -1 )

train_df['General Health'] = train_df['General Health'].mask(train_df['General Health'] == 'Fair', 0 )

train_df['General Health'] = train_df['General Health'].mask(train_df['General Health'] == 'Good', 1 )

train_df['General Health'] = train_df['General Health'].mask(train_df['General Health'] == 'Excellent', 2 )

In [14]:
train_df['General Health'].unique()

array([-2, 0, 1, -1, 2], dtype=object)

In [15]:
train_df['Education Level'].unique()

array(['High school graduate', 'College graduate', 'Some high school',
       'Some college or technical school', 'Elementary',
       'Never attended school'], dtype=object)

In [16]:
# One-hot encode Education Level and Income Level
train_df = pd.get_dummies(train_df, columns=["Education Level", "Income Level","Sex"])

In [17]:
train_df = train_df.replace({"No": 0, "Yes": 1 ,"False": 0, "True": 1 })

In [18]:
train_df

,History of HeartDisease or Attack,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Leisure Physical Activity,Heavy Alcohol Consumption,...,"Income Level_$15,000 to less than $20,000","Income Level_$20,000 to less than $25,000","Income Level_$25,000 to less than $35,000","Income Level_$35,000 to less than $50,000","Income Level_$50,000 to less than $75,000","Income Level_$75,000 or more","Income Level_($10,000 to less than $15,000","Income Level_Less than $10,000",Sex_Female,Sex_Male
0,0,1,1,1,40.68,1,0,0,0,0,...,True,False,False,False,False,False,False,False,True,False
1,0,0,0,0,24.36,1,0,0,1,0,...,False,False,False,False,False,False,False,True,True,False
2,0,1,1,1,27.33,0,0,0,0,0,...,False,False,False,False,False,True,False,False,True,False
3,0,1,0,1,27.01,0,0,0,1,0,...,False,False,False,True,False,False,False,False,True,False
5,0,1,1,1,25.11,1,0,0,1,0,...,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223079,0,0,0,1,28.20,0,0,0,0,0,...,False,False,True,False,False,False,False,False,True,False
223080,0,1,1,1,45.01,0,0,0,0,0,...,False,False,False,False,True,False,False,False,False,True
223081,0,1,1,1,18.94,0,0,1,0,0,...,False,True,False,False,False,False,False,False,True,False
223082,0,0,0,1,29.29,0,0,0,1,0,...,False,False,False,False,False,False,True,False,True,False
223083,0,1,0,1,23.67,0,0,0,0,0,...,False,False,False,False,False,False,False,True,False,True

In [19]:
train_df.describe().round(2)

,History of HeartDisease or Attack,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Leisure Physical Activity,Heavy Alcohol Consumption,Health Care Coverage,Doctor Visit Cost Barrier,General Health,Difficulty Walking,Age,Vegetable or Fruit Intake (1+ per Day)
count,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00
mean,0.09,0.43,0.42,0.96,28.40,0.44,0.04,0.15,0.76,0.06,0.95,0.08,0.49,0.17,57.67,0.88
std,0.29,0.49,0.49,0.19,6.64,0.50,0.20,0.35,0.43,0.23,0.22,0.28,1.07,0.37,16.44,0.32
min,0.00,0.00,0.00,0.00,11.28,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-2.00,0.00,18.00,0.00
25%,0.00,0.00,0.00,1.00,24.11,0.00,0.00,0.00,1.00,0.00,1.00,0.00,0.00,0.00,47.00,1.00
50%,0.00,0.00,0.00,1.00,27.28,0.00,0.00,0.00,1.00,0.00,1.00,0.00,1.00,0.00,59.00,1.00
75%,0.00,1.00,1.00,1.00,31.30,1.00,0.00,0.00,1.00,0.00,1.00,0.00,1.00,0.00,68.00,1.00
max,1.00,1.00,1.00,1.00,98.63,1.00,1.00,1.00,1.00,1.00,1.00,1.00,2.00,1.00,100.00,1.00

In [119]:
#import sys
#!{sys.executable} -m pip install "flaml[automl]" --break-system-packages

In [ ]:
#from sklearn.ensemble import HistGradientBoostingClassifier
#import pandas as pd

#TARGET = "History of HeartDisease or Attack"

# 1. Prepare training data
#X_train = train_df.drop(columns=[TARGET])
#y_train = train_df[TARGET]

# 2. Train the model (This algorithm is super fast and robust)
#print("Training model...")
#model = HistGradientBoostingClassifier(
#    max_iter=1000,          # Number of boosting iterations (similar to n_estimators)
##    learning_rate=0.05,     # How fast the model learns
#    random_state=42,
#    scoring="roc_auc"      # Good for medical/imbalanced datasets
#)
##model.fit(X_train, y_train)
#print("Training complete! accuracy score:", model.score(X_train, y_train))
# 3. Load & format the test data
#test_df = pd.read_csv("test.csv")
#test_ids = test_df["ID"]
#test_df = test_df.drop(columns=["ID"])

# Apply the identical "Yes"/"No" replacement
#test_df = test_df.replace({"No": 0, "Yes": 1})

# Automatically find any remaining text/object columns (like 'General Health', 'Education Level') 
# and one-hot encode all of them in one sweep
#text_columns = test_df.select_dtypes(include=['object']).columns.tolist()
#test_df = pd.get_dummies(test_df, columns=text_columns)

# ✨ THIS IS THE MAGIC LINE ✨
# It forces test_df to have the EXACT same columns as X_train. 
# - If test_df is missing a column X_train had, it creates it and fills with 0.
# - If test_df has an extra column X_train didn't have, it drops it.
#test_df = test_df.reindex(columns=X_train.columns, fill_value=0)

# 4. Predict
#predictions = model.predict(test_df)

# 5. Create submission file
##submission = pd.DataFrame({
 #   "ID": test_ids, 
 #   "History of HeartDisease or Attack": predictions
#})
##submission.to_csv("submission.csv", index=False)
#print("Saved submission to submission.csv")

Training model...
Training complete! accuracy score: 0.9082027002158165
Saved submission to submission.csv

In [ ]:
# 5. Create submission file
#submission = pd.DataFrame({
#    "ID": test_ids, 
#    "History of HeartDisease or Attack": predictions
#})

# Convert the 1s and 0s back into "Yes" and "No" strings
#submission["History of HeartDisease or Attack"] = submission["History of HeartDisease or Attack"].replace({
#    1: "Yes", 
 #   0: "No"
#})

#submission.to_csv("submission.csv", index=False)
#print("Saved submission to submission.csv")

Saved submission to submission.csv

In [131]:
# Run this to see the REAL error
try:
    from flaml.automl.automl import AutoML
    print("Success!")
except Exception as e:
    import traceback
    traceback.print_exc()

Success!

In [134]:
import re

# Clean column names - remove special JSON characters
X_train.columns = [re.sub(r'[^A-Za-z0-9_]', '_', col) for col in X_train.columns]

# Store the cleaned column names to apply to test later
cleaned_columns = X_train.columns.tolist()

In [136]:
# After reindex, clean test column names the same way
test_df.columns = [re.sub(r'[^A-Za-z0-9_]', '_', col) for col in test_df.columns]

In [137]:


TARGET = "History of HeartDisease or Attack"

X_train = train_df.drop(columns=[TARGET])
y_train = train_df[TARGET]

automl = AutoML()
automl.fit(
    X_train, y_train,
    task="classification",
    time_budget=120,        # seconds to search (increase for better results)
    metric="roc_auc",       # good metric for imbalanced health data
    verbose=1
)

print("Best model:", automl.best_estimator)
print("Best ROC-AUC:", automl.best_loss)

[LightGBM] [Fatal] Do not support special JSON characters in feature name.

LightGBMError: Do not support special JSON characters in feature name.

In [ ]:

# Align columns with train
test_df = test_df.reindex(columns=X_train.columns, fill_value=0)

predictions = automl.predict(test_df)

submission = pd.DataFrame({"ID": test_ids, "History of HeartDisease or Attack": predictions})
submission.to_csv("submission.csv", index=False)

In [139]:
from flaml.automl.automl import AutoML
import pandas as pd
import re

TARGET = "History of HeartDisease or Attack"

X_train = train_df.drop(columns=[TARGET])
y_train = train_df[TARGET]

# ✅ FIX: Clean ALL column names (remove spaces, parentheses, special chars)
def clean_cols(df):
    df.columns = [re.sub(r'[^A-Za-z0-9_]', '_', col) for col in df.columns]
    return df

X_train = clean_cols(X_train)

# Save cleaned column order for test later
train_columns = X_train.columns.tolist()

# Run AutoML
automl = AutoML()
automl.fit(
    X_train, y_train,
    task="classification",
    time_budget=120,
    metric="roc_auc",
    verbose=1
)

print("Best model:", automl.best_estimator)
print("Best ROC-AUC:", 1 - automl.best_loss)

Best model: lgbm
Best ROC-AUC: 0.8558705889504017

In [142]:
test_df = pd.read_csv("test.csv")
test_ids = test_df["ID"]

test_df = test_df.replace({"No": 0, "Yes": 1})
text_cols = test_df.select_dtypes(include=['object']).columns.tolist()
test_df = pd.get_dummies(test_df, columns=text_cols)
test_df = clean_cols(test_df)  # ✅ same cleaning
test_df = test_df.reindex(columns=train_columns, fill_value=0)  # ✅ align columns

predictions = automl.predict(test_df)

submission = pd.DataFrame({"ID": test_ids, "History of HeartDisease or Attack": predictions})
submission["History of HeartDisease or Attack"] = submission["History of HeartDisease or Attack"].replace({1: "Yes", 0: "No"})
submission.to_csv("submission.csv", index=False)
print("Done! Saved submission.csv")

Done! Saved submission.csv

In [144]:
submission["History of HeartDisease or Attack"] = submission["History of HeartDisease or Attack"].replace({
    "Yes": "No", 
    "No": "Yes"
})

submission.to_csv("submission.csv", index=False)
print(submission["History of HeartDisease or Attack"].value_counts())

History of HeartDisease or Attack
Yes    73986
No       375
Name: count, dtype: int64

In [20]:
from flaml.automl.automl import AutoML
from sklearn.metrics import fbeta_score
import re, pandas as pd

TARGET = "History of HeartDisease or Attack"
X_train = train_df.drop(columns=[TARGET])
y_train = train_df[TARGET]

def clean_cols(df):
    df.columns = [re.sub(r'[^A-Za-z0-9_]', '_', col) for col in df.columns]
    return df

X_train = clean_cols(X_train)
train_columns = X_train.columns.tolist()

# ✅ Custom F2 metric for FLAML
def f2_metric(X_val, y_val, estimator, labels, X_train, y_train, 
              weight_val=None, weight_train=None, *args):
    y_pred = estimator.predict(X_val)
    score = fbeta_score(y_val, y_pred, beta=2, average='binary', zero_division=0)
    return 1 - score, {"f2": score}  # return loss and metric

automl = AutoML()
automl.fit(
    X_train, y_train,
    task="classification",
    time_budget=180,
    metric=f2_metric,   # ✅ use F2 instead of roc_auc
    verbose=1
)
print("Best F2:", 1 - automl.best_loss)

Best F2: 0.1992422262869088

## version 5

In [28]:
import pandas as pd
import re
from flaml.automl.automl import AutoML
from sklearn.metrics import fbeta_score
import numpy as np

# -------------------------------------------------
# 1️⃣  PREPROCESSING FUNCTION (used for BOTH train & test)
# -------------------------------------------------
def preprocess(df, keep_columns=None):
    """
    df            : raw DataFrame (ID column already removed if present)
    keep_columns  : list of column names that the output must match
                    (used for the test set). If None → just return processed df.
    Returns processed df with numeric values only.
    """
    # ---- replace Yes/No with 1/0 (works for any column that contains these strings)
    df = df.replace({"No": 0, "Yes": 1})

    # ---- identify all remaining object (string) columns
    obj_cols = df.select_dtypes(include=["object"]).columns.tolist()

    # ---- one‑hot encode them – this automatically drops the original column
    df = pd.get_dummies(df, columns=obj_cols, drop_first=False)

    # ---- clean column names (remove spaces, parentheses, slashes, etc.)
    df.columns = [re.sub(r'[^A-Za-z0-9_]', '_', c) for c in df.columns]

    # ---- if we have a reference column order (training), align to it
    if keep_columns is not None:
        df = df.reindex(columns=keep_columns, fill_value=0)

    return df

# -------------------------------------------------
# 2️⃣  LOAD & PREPARE TRAINING DATA
# -------------------------------------------------
TARGET = "History of HeartDisease or Attack"

train_raw = pd.read_csv("train.csv")
# keep ID for possible debugging, but drop it for modeling
train_raw = train_raw.drop(columns=["ID"])

# remove rows where the target is missing (you already did this earlier)
train_raw = train_raw.dropna(subset=[TARGET])

# ---- target → numeric 0/1
y_train = train_raw[TARGET].replace({"No": 0, "Yes": 1})

# ---- features
X_train_raw = train_raw.drop(columns=[TARGET])
X_train = preprocess(X_train_raw)          # no keep_columns yet
train_columns = X_train.columns.tolist()   # remember exact order for test

print("Training shape:", X_train.shape)
print("First few columns:", train_columns[:10])

# -------------------------------------------------
# 3️⃣  DEFINE F2‑score metric for FLAML
# -------------------------------------------------
def f2_metric(X_val, y_val, estimator, labels, X_train, y_train,
              weight_val=None, weight_train=None, *args):
    """FLAML expects a *loss* (lower is better). We return 1‑F2."""
    y_pred = estimator.predict(X_val)
    f2 = fbeta_score(y_val, y_pred, beta=2, average="binary", zero_division=0)
    return 1 - f2, {"f2": f2}

# -------------------------------------------------
# 4️⃣  RUN AUTO‑ML (optimising for F2)
# -------------------------------------------------
automl = AutoML()
automl.fit(
    X_train, y_train,
    task="classification",
    time_budget=180,          # seconds – increase if you have time
    metric=f2_metric,         # custom F2 metric
    verbose=1
)

print("\n=== AUTO‑ML RESULT ===")
print("Best loss (1‑F2):", automl.best_loss)
print("Best F2 score :", 1 - automl.best_loss)
print("Best estimator :", automl.best_estimator)

# -------------------------------------------------
# 5️⃣  FIND THE BEST THRESHOLD (because we output binary Yes/No)
# -------------------------------------------------
# Get probabilities on the training set to tune the decision threshold
proba_train = automl.predict_proba(X_train)[:, 1]

best_thr, best_f2 = 0.5, 0.0
for thr in np.arange(0.1, 0.9, 0.01):
    preds = (proba_train >= thr).astype(int)
    f2 = fbeta_score(y_train, preds, beta=2, average="binary", zero_division=0)
    if f2 > best_f2:
        best_f2, best_thr = f2, thr

print(f"\nOptimal threshold on training data → {best_thr:.2f} (F2 = {best_f2:.4f})")

# -------------------------------------------------
# 6️⃣  LOAD & PREPARE TEST DATA (using the SAME PIPELINE)
# -------------------------------------------------
test_raw = pd.read_csv("test.csv")
test_ids = test_raw["ID"]
test_df_raw = test_raw.drop(columns=["ID"])

# Apply the exact same preprocessing and force column order to match training
test_df = preprocess(test_df_raw, keep_columns=train_columns)

print("\nTest shape after alignment:", test_df.shape)

# -------------------------------------------------
# 7️⃣  PREDICT & BUILD SUBMISSION
# -------------------------------------------------
proba_test = automl.predict_proba(test_df)[:, 1]
pred_binary = (proba_test >= best_thr).astype(int)

submission = pd.DataFrame({
    "ID": test_ids,
    "History of HeartDisease or Attack": pred_binary
})

# Convert back to the original Yes/No strings expected by the competition
submission["History of HeartDisease or Attack"] = submission["History of HeartDisease or Attack"].replace({
    1: "Yes",
    0: "No"
})

submission_path = "submission.csv"
submission.to_csv(submission_path, index=False)
print(f"\n✅ Submission saved to {submission_path}")
print(submission.head())

Training shape: (221390, 35)
First few columns: ['High_Blood_Pressure', 'Told_High_Cholesterol', 'Cholesterol_Checked', 'Body_Mass_Index', 'Smoked_100__Cigarettes', 'Diagnosed_Stroke', 'Diagnosed_Diabetes', 'Leisure_Physical_Activity', 'Heavy_Alcohol_Consumption', 'Health_Care_Coverage']

=== AUTO‑ML RESULT ===
Best loss (1‑F2): 0.7889513332536171
Best F2 score : 0.2110486667463829
Best estimator : extra_tree

Optimal threshold on training data → 0.11 (F2 = 0.9937)

Test shape after alignment: (74361, 35)

✅ Submission saved to submission.csv
            ID History of HeartDisease or Attack
0  test_000001                                No
1  test_000002                                No
2  test_000003                               Yes
3  test_000004                                No
4  test_000005                                No

## Version6

In [29]:


# -------------------------------------------------
# 0️⃣  Imports
# -------------------------------------------------
import pandas as pd, re, numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import fbeta_score
from xgboost import XGBClassifier

# -------------------------------------------------
# 1️⃣  Preprocessing (shared for train & test)
# -------------------------------------------------
def preprocess(df, keep_columns=None):
    df = df.replace({"No": 0, "Yes": 1})
    obj_cols = df.select_dtypes(include=["object"]).columns.tolist()
    df = pd.get_dummies(df, columns=obj_cols, drop_first=False)
    df.columns = [re.sub(r'[^A-Za-z0-9_]', '_', c) for c in df.columns]
    if keep_columns is not None:
        df = df.reindex(columns=keep_columns, fill_value=0)
    return df

# -------------------------------------------------
# 2️⃣  Load & prepare training data
# -------------------------------------------------
TARGET = "History of HeartDisease or Attack"
train_raw = pd.read_csv("train.csv").drop(columns=["ID"])
train_raw = train_raw.dropna(subset=[TARGET])

y = train_raw[TARGET].replace({"No": 0, "Yes": 1})
X_raw = train_raw.drop(columns=[TARGET])
X = preprocess(X_raw)
train_cols = X.columns.tolist()

# -------------------------------------------------
# 3️⃣  Train/validation split (20% for validation)
# -------------------------------------------------
X_tr, X_val, y_tr, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


# -------------------------------------------------
# 4️⃣  Model – XGBoost with class weighting
# -------------------------------------------------
scale_pos_weight = (y_tr == 0).sum() / (y_tr == 1).sum()
model = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    scale_pos_weight=scale_pos_weight,
    n_jobs=4,
    random_state=42,
)

model.fit(X_tr, y_tr)

# -------------------------------------------------
# 5️⃣  Find best threshold on validation set (optimise F2)
# -------------------------------------------------
proba_val = model.predict_proba(X_val)[:, 1]

best_thr, best_f2 = 0.5, 0.0
for thr in np.arange(0.1, 0.9, 0.01):
    preds = (proba_val >= thr).astype(int)
    f2 = fbeta_score(y_val, preds, beta=2, average="binary", zero_division=0)
    if f2 > best_f2:
        best_f2, best_thr = f2, thr

print(f"\nOptimal threshold on validation → {best_thr:.3f}")
print(f"Validation F2 score → {best_f2:.5f}")

# -------------------------------------------------
# 6️⃣  Load & preprocess test data (same pipeline)
# -------------------------------------------------
test_raw = pd.read_csv("test.csv")
test_ids = test_raw["ID"]
test_df = preprocess(test_raw.drop(columns=["ID"]), keep_columns=train_cols)

# -------------------------------------------------
# 7️⃣  Predict on test & build submission
# -------------------------------------------------
proba_test = model.predict_proba(test_df)[:, 1]
test_pred = (proba_test >= best_thr).astype(int)

submission = pd.DataFrame({
    "ID": test_ids,
    "History of HeartDisease or Attack": test_pred
})
submission["History of HeartDisease or Attack"] = submission["History of HeartDisease or Attack"].replace({
    1: "Yes",
    0: "No"
})

submission_path = "submission.csv"
submission.to_csv(submission_path, index=False)
print(f"\n✅ Saved submission → {submission_path}")
print(submission.head())

Optimal threshold on validation → 0.530
Validation F2 score → 0.53760

✅ Saved submission → submission.csv
            ID History of HeartDisease or Attack
0  test_000001                               Yes
1  test_000002                                No
2  test_000003                               Yes
3  test_000004                                No
4  test_000005                                No