In [ ]:
# file "https://www.kaggle.com/settings"
#files.upload() #upload kaggle.json (Legacy API Credentials)

#!mkdir -p ~/.kaggle/

# Move the uploaded kaggle.json file to the .kaggle directory
#!mv kaggle.json ~/.kaggle/

# Set secure permissions for the API key file (read-only for owner)
#!chmod 600 ~/.kaggle/kaggle.json

# ! kaggle competitions download -c super-ai-engineer-ss-6-heart-disease-prediction

# Load the data from kaggle and upload here.
# !unzip aggle competitions download -c super-ai-engineer-ss-6-heart-disease-prediction.zip

In [ ]:
import pandas as pd
import math

In [ ]:
train_df = pd.read_csv("train.csv")
train_df.pop("ID")

train_df.head()

,History of HeartDisease or Attack,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Leisure Physical Activity,Heavy Alcohol Consumption,Health Care Coverage,Doctor Visit Cost Barrier,General Health,Difficulty Walking,Sex,Education Level,Income Level,Age,Vegetable or Fruit Intake (1+ per Day)
0,No,Yes,Yes,Yes,40.68,Yes,No,No,No,No,Yes,No,Very Poor,Yes,Female,High school graduate,"$15,000 to less than $20,000",64,Yes
1,No,No,No,No,24.36,Yes,No,No,Yes,No,No,Yes,Fair,No,Female,College graduate,"Less than $10,000",50,No
2,No,Yes,Yes,Yes,27.33,No,No,No,No,No,Yes,Yes,Very Poor,Yes,Female,High school graduate,"$75,000 or more",61,Yes
3,No,Yes,No,Yes,27.01,No,No,No,Yes,No,Yes,No,Good,No,Female,Some high school,"$35,000 to less than $50,000",74,Yes
4,NaN,Yes,Yes,Yes,34.56,Yes,No,No,Yes,No,Yes,Yes,Very Poor,Yes,Male,Some high school,"$15,000 to less than $20,000",98,Yes

In [ ]:
train_df.shape

(223084, 19)

In [ ]:
train_df.describe()

       Body Mass Index            Age
count    211302.000000  223084.000000
mean         28.189817      54.739717
std           6.688447      17.795140
min          11.210000      18.000000
25%          23.880000      42.000000
50%          27.070000      56.000000
75%          31.100000      67.000000
max          98.630000     100.000000

In [ ]:
shape_Before_Clean = train_df.shape
train_df.shape

(223084, 19)

In [ ]:
train_df.isnull().sum()

History of HeartDisease or Attack          1694
High Blood Pressure                           0
Told High Cholesterol                     32186
Cholesterol Checked                           0
Body Mass Index                           11782
Smoked 100+ Cigarettes                        1
Diagnosed Stroke                              0
Diagnosed Diabetes                            3
Leisure Physical Activity                     0
Heavy Alcohol Consumption                     0
Health Care Coverage                          0
Doctor Visit Cost Barrier                     1
General Health                                1
Difficulty Walking                            3
Sex                                           0
Education Level                               0
Income Level                                  0
Age                                           0
Vegetable or Fruit Intake (1+ per Day)        0
dtype: int64

In [ ]:
# first version drop all missing Data
# drop all data that No hx of heart
train_df = train_df.dropna(subset=["History of HeartDisease or Attack"])
train_df.isnull().sum()

History of HeartDisease or Attack             0
High Blood Pressure                           0
Told High Cholesterol                     32043
Cholesterol Checked                           0
Body Mass Index                           11725
Smoked 100+ Cigarettes                        1
Diagnosed Stroke                              0
Diagnosed Diabetes                            3
Leisure Physical Activity                     0
Heavy Alcohol Consumption                     0
Health Care Coverage                          0
Doctor Visit Cost Barrier                     1
General Health                                1
Difficulty Walking                            3
Sex                                           0
Education Level                               0
Income Level                                  0
Age                                           0
Vegetable or Fruit Intake (1+ per Day)        0
dtype: int64

In [ ]:
train_df.shape

(221390, 19)

In [ ]:
shape_After_Clean = train_df.shape
Data_Loss = round(abs((shape_Before_Clean[0] - shape_After_Clean[0])/shape_Before_Clean[0] * 100 ),2)
print("Data loss : "+str(Data_Loss)+" %")

Data loss : 0.76 %

In [ ]:
train_df.head()

,History of HeartDisease or Attack,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Leisure Physical Activity,Heavy Alcohol Consumption,Health Care Coverage,Doctor Visit Cost Barrier,General Health,Difficulty Walking,Sex,Education Level,Income Level,Age,Vegetable or Fruit Intake (1+ per Day)
0,No,Yes,Yes,Yes,40.68,Yes,No,No,No,No,Yes,No,Very Poor,Yes,Female,High school graduate,"$15,000 to less than $20,000",64,Yes
1,No,No,No,No,24.36,Yes,No,No,Yes,No,No,Yes,Fair,No,Female,College graduate,"Less than $10,000",50,No
2,No,Yes,Yes,Yes,27.33,No,No,No,No,No,Yes,Yes,Very Poor,Yes,Female,High school graduate,"$75,000 or more",61,Yes
3,No,Yes,No,Yes,27.01,No,No,No,Yes,No,Yes,No,Good,No,Female,Some high school,"$35,000 to less than $50,000",74,Yes
5,No,Yes,Yes,Yes,25.11,Yes,No,No,Yes,No,Yes,No,Good,No,Male,College graduate,"$75,000 or more",67,Yes

In [ ]:
train_df['General Health'].unique()

array(['Very Poor', 'Fair', 'Good', 'Poor', 'Excellent'], dtype=object)

In [ ]:
# due to General Health may ordinal data change in to int

train_df['General Health'] = train_df['General Health'].mask(train_df['General Health'] == 'Very Poor', -2 )

train_df['General Health'] = train_df['General Health'].mask(train_df['General Health'] == 'Poor', -1 )

train_df['General Health'] = train_df['General Health'].mask(train_df['General Health'] == 'Fair', 0 )

train_df['General Health'] = train_df['General Health'].mask(train_df['General Health'] == 'Good', 1 )

train_df['General Health'] = train_df['General Health'].mask(train_df['General Health'] == 'Excellent', 2 )

In [ ]:
train_df['General Health'].unique()

array([-2, 0, 1, -1, 2], dtype=object)

In [ ]:
train_df['Education Level'].unique()

array(['High school graduate', 'College graduate', 'Some high school',
       'Some college or technical school', 'Elementary',
       'Never attended school'], dtype=object)

In [ ]:
# One-hot encode Education Level and Income Level
train_df = pd.get_dummies(train_df, columns=["Education Level", "Income Level","Sex"])

In [ ]:
train_df = train_df.replace({"No": 0, "Yes": 1 ,"False": 0, "True": 1 })

In [ ]:
train_df

,History of HeartDisease or Attack,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Leisure Physical Activity,Heavy Alcohol Consumption,...,"Income Level_$15,000 to less than $20,000","Income Level_$20,000 to less than $25,000","Income Level_$25,000 to less than $35,000","Income Level_$35,000 to less than $50,000","Income Level_$50,000 to less than $75,000","Income Level_$75,000 or more","Income Level_($10,000 to less than $15,000","Income Level_Less than $10,000",Sex_Female,Sex_Male
0,0,1,1,1,40.68,1,0,0,0,0,...,True,False,False,False,False,False,False,False,True,False
1,0,0,0,0,24.36,1,0,0,1,0,...,False,False,False,False,False,False,False,True,True,False
2,0,1,1,1,27.33,0,0,0,0,0,...,False,False,False,False,False,True,False,False,True,False
3,0,1,0,1,27.01,0,0,0,1,0,...,False,False,False,True,False,False,False,False,True,False
5,0,1,1,1,25.11,1,0,0,1,0,...,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223079,0,0,0,1,28.20,0,0,0,0,0,...,False,False,True,False,False,False,False,False,True,False
223080,0,1,1,1,45.01,0,0,0,0,0,...,False,False,False,False,True,False,False,False,False,True
223081,0,1,1,1,18.94,0,0,1,0,0,...,False,True,False,False,False,False,False,False,True,False
223082,0,0,0,1,29.29,0,0,0,1,0,...,False,False,False,False,False,False,True,False,True,False
223083,0,1,0,1,23.67,0,0,0,0,0,...,False,False,False,False,False,False,False,True,False,True

In [ ]:
train_df.describe().round(2)

,History of HeartDisease or Attack,High Blood Pressure,Told High Cholesterol,Cholesterol Checked,Body Mass Index,Smoked 100+ Cigarettes,Diagnosed Stroke,Diagnosed Diabetes,Leisure Physical Activity,Heavy Alcohol Consumption,Health Care Coverage,Doctor Visit Cost Barrier,General Health,Difficulty Walking,Age,Vegetable or Fruit Intake (1+ per Day)
count,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00,179319.00
mean,0.09,0.43,0.42,0.96,28.40,0.44,0.04,0.15,0.76,0.06,0.95,0.08,0.49,0.17,57.67,0.88
std,0.29,0.49,0.49,0.19,6.64,0.50,0.20,0.35,0.43,0.23,0.22,0.28,1.07,0.37,16.44,0.32
min,0.00,0.00,0.00,0.00,11.28,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-2.00,0.00,18.00,0.00
25%,0.00,0.00,0.00,1.00,24.11,0.00,0.00,0.00,1.00,0.00,1.00,0.00,0.00,0.00,47.00,1.00
50%,0.00,0.00,0.00,1.00,27.28,0.00,0.00,0.00,1.00,0.00,1.00,0.00,1.00,0.00,59.00,1.00
75%,0.00,1.00,1.00,1.00,31.30,1.00,0.00,0.00,1.00,0.00,1.00,0.00,1.00,0.00,68.00,1.00
max,1.00,1.00,1.00,1.00,98.63,1.00,1.00,1.00,1.00,1.00,1.00,1.00,2.00,1.00,100.00,1.00

## autoLM

## XGBClassifier(

## version 1

In [ ]:
# -------------------------------------------------
# 0️⃣  Imports
# -------------------------------------------------
import pandas as pd
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sklearn.metrics import fbeta_score
from sklearn.impute import SimpleImputer
from xgboost import XGBClassifier

# -------------------------------------------------
# 1️⃣  Preprocessing function (median imputation)
# -------------------------------------------------
def preprocess(df, keep_columns=None):
    """
    df            : raw DataFrame (ID column already removed if present)
    keep_columns  : list of column names that the output must match.
                    Used for the test set to force exact column order.
    Returns a DataFrame where:
        • Yes/No → 1/0
        • All object columns are one‑hot encoded
        • All numeric columns are median‑imputed
        • Column names are cleaned (no spaces, parentheses, etc.)
        • Optional re‑indexing to a reference column order
    """
    # 1) Yes/No → 1/0 (works for any column that contains these strings)
    df = df.replace({"No": 0, "Yes": 1})

    # 2) One‑hot encode every remaining object (categorical) column
    obj_cols = df.select_dtypes(include=["object"]).columns.tolist()
    df = pd.get_dummies(df, columns=obj_cols, drop_first=False)

    # 3) Median imputation for all numeric columns
    num_cols = df.select_dtypes(include=[np.number]).columns
    imputer = SimpleImputer(strategy="median")
    df[num_cols] = imputer.fit_transform(df[num_cols])

    # 4) Clean column names (remove spaces, parentheses, slashes, etc.)
    df.columns = [re.sub(r'[^A-Za-z0-9_]', '_', c) for c in df.columns]

    # 5) Align to a reference column order if we have one (test set)
    if keep_columns is not None:
        df = df.reindex(columns=keep_columns, fill_value=0)

    return df

# -------------------------------------------------
# 2️⃣  Load & prepare training data
# -------------------------------------------------
TARGET = "History of HeartDisease or Attack"

train_raw = pd.read_csv("train.csv").drop(columns=["ID"])
# Drop rows where the target itself is missing
train_raw = train_raw.dropna(subset=[TARGET])

y = train_raw[TARGET].replace({"No": 0, "Yes": 1})
X_raw = train_raw.drop(columns=[TARGET])

# Apply preprocessing (median imputation happens inside)
X = preprocess(X_raw)
train_columns = X.columns.tolist()          # remember exact order for the test set

print("✅ Training shape after imputation:", X.shape)

# -------------------------------------------------
# 3️⃣  Train / validation split (20% for validation)
# -------------------------------------------------
X_tr, X_val, y_tr, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# -------------------------------------------------
# 4️⃣  Model – XGBoost with class weighting (helps F2)
# -------------------------------------------------
scale_pos_weight = (y_tr == 0).sum() / (y_tr == 1).sum()

model = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    scale_pos_weight=scale_pos_weight,
    n_jobs=4,
    random_state=42,
)

model.fit(X_tr, y_tr)

# -------------------------------------------------
# 5️⃣  Find the best threshold on the validation set (optimise F2)
# -------------------------------------------------
proba_val = model.predict_proba(X_val)[:, 1]

best_thr, best_f2 = 0.5, 0.0
for thr in np.arange(0.1, 0.9, 0.01):
    preds = (proba_val >= thr).astype(int)
    f2 = fbeta_score(y_val, preds, beta=2, average="binary", zero_division=0)
    if f2 > best_f2:
        best_f2, best_thr = f2, thr

print(f"\n🔎 Optimal threshold on validation → {best_thr:.3f}")
print(f"📈 Validation F2 score → {best_f2:.5f}")

# -------------------------------------------------
# 6️⃣  Load & preprocess test data (same pipeline)
# -------------------------------------------------
test_raw = pd.read_csv("test.csv")
test_ids = test_raw["ID"]
test_df_raw = test_raw.drop(columns=["ID"])

# Apply the exact same preprocessing and force column order to match training
test_df = preprocess(test_df_raw, keep_columns=train_columns)

print("\n✅ Test shape after imputation & alignment:", test_df.shape)

# -------------------------------------------------
# 7️⃣  Predict on test & build submission (binary Yes/No)
# -------------------------------------------------
proba_test = model.predict_proba(test_df)[:, 1]
test_pred = (proba_test >= best_thr).astype(int)

submission = pd.DataFrame({
    "ID": test_ids,
    "History of HeartDisease or Attack": test_pred
})

# Convert back to the original Yes/No strings expected by the competition
submission["History of HeartDisease or Attack"] = submission["History of HeartDisease or Attack"].replace({
    1: "Yes",
    0: "No"
})

submission_path = "submission.csv"
submission.to_csv(submission_path, index=False)

print(f"\n🚀 Submission saved to **{submission_path}**")
print(submission.head())

✅ Training shape after imputation: (221390, 35)

🔎 Optimal threshold on validation → 0.570
📈 Validation F2 score → 0.53803

✅ Test shape after imputation & alignment: (74361, 35)

🚀 Submission saved to **submission.csv**
            ID History of HeartDisease or Attack
0  test_000001                                No
1  test_000002                                No
2  test_000003                               Yes
3  test_000004                                No
4  test_000005                                No

In [ ]:
# -------------------------------------------------
# 0️⃣  Imports
# -------------------------------------------------
import pandas as pd
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sklearn.metrics import fbeta_score
from sklearn.impute import SimpleImputer
from flaml.automl.automl import AutoML
import sys

# -------------------------------------------------
# 1️⃣  Helper: preprocessing with median imputation
# -------------------------------------------------
def preprocess(df, keep_columns=None):
    """
    df            : raw DataFrame (ID column already removed if present)
    keep_columns  : list of column names that the output must match.
                    Used for the test set to force exact column order.
    Returns a DataFrame where:
        • Yes/No → 1/0
        • All object columns are one‑hot encoded
        • All numeric columns are median‑imputed
        • Column names are cleaned (no spaces, parentheses, etc.)
        • Optional re‑indexing to a reference column order
    """
    # 1) Yes/No → 1/0
    df = df.replace({"No": 0, "Yes": 1})

    # 2) One‑hot encode every remaining object column
    obj_cols = df.select_dtypes(include=["object"]).columns.tolist()
    df = pd.get_dummies(df, columns=obj_cols, drop_first=False)

    # 3) Median imputation for all numeric columns
    num_cols = df.select_dtypes(include=[np.number]).columns
    imputer = SimpleImputer(strategy="median")
    df[num_cols] = imputer.fit_transform(df[num_cols])

    # 4) Clean column names (remove spaces, parentheses, slashes, etc.)
    df.columns = [re.sub(r'[^A-Za-z0-9_]', '_', c) for c in df.columns]

    # 5) Align to a reference column order if provided (test set)
    if keep_columns is not None:
        df = df.reindex(columns=keep_columns, fill_value=0)

    return df

# -------------------------------------------------
# 2️⃣  Load & prepare training data
# -------------------------------------------------
TARGET = "History of HeartDisease or Attack"

# Load train, drop the ID column, and drop rows where the target is missing
train_raw = pd.read_csv("train.csv").drop(columns=["ID"])
train_raw = train_raw.dropna(subset=[TARGET])

# Target → numeric 0/1
y = train_raw[TARGET].replace({"No": 0, "Yes": 1})

# Features (everything except the target)
X_raw = train_raw.drop(columns=[TARGET])

# Apply preprocessing (includes median imputation)
X = preprocess(X_raw)

# Store the exact column order – we will reuse it for the test set
train_cols = X.columns.tolist()

print("✅ Training shape after preprocessing:", X.shape)
print("Number of features (columns):", len(train_cols))

Data_Loss = round(abs((shape_Before_Clean[0] - X.shape[0])/shape_Before_Clean[0]  * 100 ),2)
print("Data loss : "+str(Data_Loss)+" %")


# -------------------------------------------------
# 3️⃣  Train/validation split (20% for validation)
# -------------------------------------------------
X_tr, X_val, y_tr, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# -------------------------------------------------
# 4️⃣  Custom F2‑loss for FLAML
# -------------------------------------------------
def f2_loss(X_val, y_val, estimator, labels, X_train, y_train,
            weight_val=None, weight_train=None, *args):
    """
    FLAML expects a *loss* (lower is better). We return 1‑F2.
    """
    y_pred = estimator.predict(X_val)
    f2 = fbeta_score(y_val, y_pred, beta=2, average="binary", zero_division=0)
    return 1 - f2, {"f2": f2}

# -------------------------------------------------
# 5️⃣  AutoML training (optimising for F2)
# -------------------------------------------------
automl = AutoML()
automl.fit(
    X_tr, y_tr,
    task="classification",
    time_budget=300,          # seconds – increase if you have more time
    metric=f2_loss,           # optimise for F2
    verbose=1
)

print("\n🔎 Best loss (1‑F2):", automl.best_loss)
print("🏆 Best F2 score :", 1 - automl.best_loss)
print("🧩 Best estimator :", automl.best_estimator)

# -------------------------------------------------
# 6️⃣  Find optimal decision threshold on the validation set
# -------------------------------------------------
proba_val = automl.predict_proba(X_val)[:, 1]

best_thr, best_f2 = 0.5, 0.0
for thr in np.arange(0.1, 0.9, 0.01):
    preds = (proba_val >= thr).astype(int)
    f2 = fbeta_score(y_val, preds, beta=2, average="binary", zero_division=0)
    if f2 > best_f2:
        best_f2, best_thr = f2, thr

print(f"\nOptimal threshold on validation → {best_thr:.3f}")
print(f"Validation F2 score          → {best_f2:.5f}")

# -------------------------------------------------
# 7️⃣  Load & preprocess test data (same pipeline)
# -------------------------------------------------
test_raw = pd.read_csv("test.csv")
test_ids = test_raw["ID"]
test_df_raw = test_raw.drop(columns=["ID"])

# Apply the exact same preprocessing and force column order to match training
test_df = preprocess(test_df_raw, keep_columns=train_cols)

print("\n✅ Test shape after preprocessing & alignment:", test_df.shape)

# -------------------------------------------------
# 8️⃣  Predict on test & build submission (binary Yes/No)
# -------------------------------------------------
proba_test = automl.predict_proba(test_df)[:, 1]
test_pred = (proba_test >= best_thr).astype(int)

submission = pd.DataFrame({
    "ID": test_ids,
    "History of HeartDisease or Attack": test_pred
})

# Convert back to the original Yes/No strings expected by the competition
submission["History of HeartDisease or Attack"] = submission["History of HeartDisease or Attack"].replace({
    1: "Yes",
    0: "No"
})

submission_path = "submission.csv"
submission.to_csv(submission_path, index=False)

print(f"\n🚀 Submission saved to **{submission_path}**")
print(submission.head())

✅ Training shape after preprocessing: (221390, 35)
Number of features (columns): 35
Data loss : 0.76 %

🔎 Best loss (1‑F2): 0.7326322026366464
🏆 Best F2 score : 0.2673677973633536
🧩 Best estimator : lgbm

Optimal threshold on validation → 0.100
Validation F2 score          → 0.44011

✅ Test shape after preprocessing & alignment: (74361, 35)

🚀 Submission saved to **submission.csv**
            ID History of HeartDisease or Attack
0  test_000001                               Yes
1  test_000002                                No
2  test_000003                               Yes
3  test_000004                                No
4  test_000005                                No

## version 2
better features, an ensemble of strong models, and aggressive recall optimization.
 distorts probability calibration, causing the ensemble to predict poorly calibrated scores

In [ ]:
# -------------------------------------------------
# 0️⃣  Imports
# -------------------------------------------------
import pandas as pd
import numpy as np
import re
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import fbeta_score
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
import subprocess, sys

subprocess.run([sys.executable, "-m", "pip", "install", "lightgbm", "catboost", "--break-system-packages", "-q"])
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

# -------------------------------------------------
# 1️⃣  Preprocessing (NO one-hot for CatBoost – keep object cols)
# -------------------------------------------------
def encode_general_health(df):
    """General Health is ordinal — encode as number instead of one-hot"""
    mapping = {"Very Poor": 0, "Poor": 1, "Fair": 2, "Good": 3, "Excellent": 4}
    if "General Health" in df.columns:
        df["General Health"] = df["General Health"].map(mapping).fillna(2)
    return df

def preprocess(df, keep_columns=None):
    df = df.copy()
    # Ordinal encode General Health BEFORE yes/no replacement
    df = encode_general_health(df)
    df = df.replace({"No": 0, "Yes": 1})
    obj_cols = df.select_dtypes(include=["object"]).columns.tolist()
    df = pd.get_dummies(df, columns=obj_cols, drop_first=False)
    num_cols = df.select_dtypes(include=[np.number]).columns
    imputer = SimpleImputer(strategy="median")
    df[num_cols] = imputer.fit_transform(df[num_cols])
    df.columns = [re.sub(r'[^A-Za-z0-9_]', '_', c) for c in df.columns]
    if keep_columns is not None:
        df = df.reindex(columns=keep_columns, fill_value=0)
    return df

def engineer(df):
    """Add risk-factor interaction features"""
    df = df.copy()
    if "Body_Mass_Index" in df.columns and "Age" in df.columns:
        df["BMI_x_Age"]      = df["Body_Mass_Index"] * df["Age"]
        df["obese"]          = (df["Body_Mass_Index"] >= 30).astype(int)
        df["senior"]         = (df["Age"] >= 60).astype(int)
    risk_cols = ["High_Blood_Pressure","Told_High_Cholesterol","Diagnosed_Stroke",
                 "Diagnosed_Diabetes","Smoked_100__Cigarettes","Difficulty_Walking"]
    existing = [c for c in risk_cols if c in df.columns]
    df["risk_score"] = df[existing].sum(axis=1)
    if "High_Blood_Pressure" in df.columns and "senior" in df.columns:
        df["bp_x_senior"]   = df["High_Blood_Pressure"] * df["senior"]
        df["diab_x_senior"] = df.get("Diagnosed_Diabetes", 0) * df["senior"]
    return df

# -------------------------------------------------
# 2️⃣  Load & prepare training data
# -------------------------------------------------
TARGET = "History of HeartDisease or Attack"

train_raw = pd.read_csv("train.csv").drop(columns=["ID"])
train_raw = train_raw.dropna(subset=[TARGET])

y = train_raw[TARGET].replace({"No": 0, "Yes": 1}).values

X = preprocess(train_raw.drop(columns=[TARGET]))
X = engineer(X)
train_cols = X.columns.tolist()
X = X.values   # numpy for speed

pos_weight = (y == 0).sum() / (y == 1).sum()
print(f"✅ Training shape: {X.shape}")
print(f"   scale_pos_weight (natural ratio): {pos_weight:.1f}")

# -------------------------------------------------
# 3️⃣  5-Fold OOF stacking (NO SMOTE – use scale_pos_weight instead)
# -------------------------------------------------
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

oof_xgb  = np.zeros(len(y))
oof_lgbm = np.zeros(len(y))
oof_cat  = np.zeros(len(y))

models_xgb, models_lgbm, models_cat = [], [], []

for fold, (tr_idx, val_idx) in enumerate(skf.split(X, y)):
    X_tr, X_val = X[tr_idx], X[val_idx]
    y_tr, y_val = y[tr_idx], y[val_idx]

    # XGBoost
    xgb = XGBClassifier(
        n_estimators=700, learning_rate=0.02, max_depth=6,
        min_child_weight=3, gamma=0.05,
        subsample=0.85, colsample_bytree=0.75,
        reg_alpha=0.05, reg_lambda=1.0,
        scale_pos_weight=pos_weight * 1.5,   # amplify minority class
        objective="binary:logistic", eval_metric="logloss",
        early_stopping_rounds=40, n_jobs=4, random_state=42,
    )
    xgb.fit(X_tr, y_tr, eval_set=[(X_val, y_val)], verbose=False)
    oof_xgb[val_idx] = xgb.predict_proba(X_val)[:, 1]
    models_xgb.append(xgb)

    # LightGBM
    lgbm = LGBMClassifier(
        n_estimators=700, learning_rate=0.02, num_leaves=63,
        min_child_samples=20, subsample=0.85, colsample_bytree=0.75,
        reg_alpha=0.05, reg_lambda=1.0,
        scale_pos_weight=pos_weight * 1.5,
        n_jobs=4, random_state=42, verbose=-1,
    )
    lgbm.fit(X_tr, y_tr, eval_set=[(X_val, y_val)],
             callbacks=[])
    oof_lgbm[val_idx] = lgbm.predict_proba(X_val)[:, 1]
    models_lgbm.append(lgbm)

    # CatBoost
    cat = CatBoostClassifier(
        iterations=700, learning_rate=0.02, depth=6,
        scale_pos_weight=pos_weight * 1.5,
        eval_metric="Logloss",
        early_stopping_rounds=40, random_seed=42, verbose=0,
    )
    cat.fit(X_tr, y_tr, eval_set=(X_val, y_val))
    oof_cat[val_idx] = cat.predict_proba(X_val)[:, 1]
    models_cat.append(cat)

    # quick F2 check per fold
    blend = 0.4*oof_xgb[val_idx] + 0.35*oof_lgbm[val_idx] + 0.25*oof_cat[val_idx]
    f2 = fbeta_score(y_val, blend >= 0.3, beta=2, average="binary", zero_division=0)
    print(f"  Fold {fold+1} F2 @ 0.30: {f2:.5f}")

# -------------------------------------------------
# 4️⃣  Blend all 3 models & find optimal F2 threshold
# -------------------------------------------------
oof_blend = 0.40 * oof_xgb + 0.35 * oof_lgbm + 0.25 * oof_cat

best_thr, best_f2 = 0.5, 0.0
for thr in np.arange(0.05, 0.9, 0.005):
    f2 = fbeta_score(y, (oof_blend >= thr).astype(int),
                     beta=2, average="binary", zero_division=0)
    if f2 > best_f2:
        best_f2, best_thr = f2, thr

print(f"\n🔎 Optimal threshold → {best_thr:.3f}")
print(f"📈 OOF Blended F2   → {best_f2:.5f}  (target ≥ 0.70)")

# -------------------------------------------------
# 5️⃣  Load & preprocess test data (same pipeline)
# -------------------------------------------------
test_raw = pd.read_csv("test.csv")
test_ids = test_raw["ID"]
test_df  = preprocess(test_raw.drop(columns=["ID"]), keep_columns=None)
test_df  = engineer(test_df)
test_df  = test_df.reindex(columns=train_cols, fill_value=0)
X_test   = test_df.values

# -------------------------------------------------
# 6️⃣  Average all 5 folds of each model on test data
# -------------------------------------------------
proba_xgb  = np.mean([m.predict_proba(X_test)[:, 1] for m in models_xgb],  axis=0)
proba_lgbm = np.mean([m.predict_proba(X_test)[:, 1] for m in models_lgbm], axis=0)
proba_cat  = np.mean([m.predict_proba(X_test)[:, 1] for m in models_cat],  axis=0)

proba_test = 0.40 * proba_xgb + 0.35 * proba_lgbm + 0.25 * proba_cat
test_pred  = (proba_test >= best_thr).astype(int)

# -------------------------------------------------
# 7️⃣  Save submission
# -------------------------------------------------
submission = pd.DataFrame({
    "ID": test_ids,
    "History of HeartDisease or Attack": test_pred
})
submission["History of HeartDisease or Attack"] = submission["History of HeartDisease or Attack"].replace({
    1: "Yes", 0: "No"
})
submission.to_csv("submission.csv", index=False)

print(f"\n🚀 Submission saved!")
print(submission["History of HeartDisease or Attack"].value_counts())

✅ Training shape: (221390, 37)
   scale_pos_weight (natural ratio): 11.3
  Fold 1 F2 @ 0.30: 0.47487
  Fold 2 F2 @ 0.30: 0.47626
  Fold 3 F2 @ 0.30: 0.47728
  Fold 4 F2 @ 0.30: 0.47370
  Fold 5 F2 @ 0.30: 0.47534

🔎 Optimal threshold → 0.650
📈 OOF Blended F2   → 0.54259  (target ≥ 0.70)

🚀 Submission saved!
History of HeartDisease or Attack
No     52410
Yes    21951
Name: count, dtype: int64

## version 3

In [ ]:
# -------------------------------------------------
# 0️⃣  Imports
# -------------------------------------------------
import pandas as pd, numpy as np, re, sys, subprocess
import warnings; warnings.filterwarnings("ignore")

subprocess.run([sys.executable, "-m", "pip", "install",
                "optuna", "lightgbm", "--break-system-packages", "-q"])

import optuna
from optuna.samplers import TPESampler
optuna.logging.set_verbosity(optuna.logging.WARNING)

from lightgbm import LGBMClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import fbeta_score
from sklearn.impute import SimpleImputer

# -------------------------------------------------
# 1️⃣  Preprocessing
# -------------------------------------------------
def preprocess(df, keep_columns=None):
    df = df.copy()
    df = df.replace({"No": 0, "Yes": 1})
    # Ordinal-encode General Health (it's NOT one-hot, it has natural order)
    gh_map = {"Very Poor":-2, "Poor":-1, "Fair":0, "Good":1, "Excellent":2}
    if "General Health" in df.columns:
        df["General Health"] = df["General Health"].map(gh_map).fillna(0)
    obj_cols = df.select_dtypes(include=["object"]).columns.tolist()
    df = pd.get_dummies(df, columns=obj_cols, drop_first=False)
    num_cols = df.select_dtypes(include=[np.number]).columns
    imputer = SimpleImputer(strategy="median")
    df[num_cols] = imputer.fit_transform(df[num_cols])
    df.columns = [re.sub(r'[^A-Za-z0-9_]', '_', c) for c in df.columns]
    if keep_columns is not None:
        df = df.reindex(columns=keep_columns, fill_value=0)
    return df

def engineer(df):
    df = df.copy()
    if "Body_Mass_Index" in df.columns:
        df["obese"]  = (df["Body_Mass_Index"] >= 30).astype(int)
    if "Age" in df.columns:
        df["senior"] = (df["Age"] >= 60).astype(int)
    risk_cols = ["High_Blood_Pressure","Told_High_Cholesterol",
                 "Diagnosed_Stroke","Diagnosed_Diabetes",
                 "Smoked_100__Cigarettes","Difficulty_Walking"]
    ex = [c for c in risk_cols if c in df.columns]
    df["risk_score"] = df[ex].sum(axis=1)
    if "High_Blood_Pressure" in df.columns and "senior" in df.columns:
        df["bp_x_senior"]    = df["High_Blood_Pressure"] * df["senior"]
        df["diab_x_senior"]  = df.get("Diagnosed_Diabetes", 0) * df["senior"]
        df["obese_x_senior"] = df.get("obese", 0) * df["senior"]
    return df

# -------------------------------------------------
# 2️⃣  Load & prepare data
# -------------------------------------------------
TARGET = "History of HeartDisease or Attack"
train_raw = pd.read_csv("train.csv").drop(columns=["ID"]).dropna(subset=[TARGET])
y = train_raw[TARGET].replace({"No": 0, "Yes": 1}).values
X = engineer(preprocess(train_raw.drop(columns=[TARGET])))
train_cols = X.columns.tolist()
X_arr = X.values
pos_weight = (y == 0).sum() / (y == 1).sum()
print(f"✅ Training shape: {X_arr.shape} | pos_weight: {pos_weight:.1f}")

# -------------------------------------------------
# 3️⃣  Optuna objective: 3-fold CV, optimize F2 directly
# -------------------------------------------------
skf3 = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

def objective(trial):
    params = dict(
        n_estimators      = trial.suggest_int("n_estimators", 300, 1500),
        learning_rate     = trial.suggest_float("learning_rate", 0.005, 0.1, log=True),
        num_leaves        = trial.suggest_int("num_leaves", 31, 255),
        max_depth         = trial.suggest_int("max_depth", 4, 10),
        min_child_samples = trial.suggest_int("min_child_samples", 5, 50),
        subsample         = trial.suggest_float("subsample", 0.5, 1.0),
        colsample_bytree  = trial.suggest_float("colsample_bytree", 0.4, 1.0),
        reg_alpha         = trial.suggest_float("reg_alpha", 1e-3, 10, log=True),
        reg_lambda        = trial.suggest_float("reg_lambda", 1e-3, 10, log=True),
        # Key: let Optuna decide how much to amplify the minority class
        scale_pos_weight  = trial.suggest_float("scale_pos_weight",
                                                pos_weight * 0.5,
                                                pos_weight * 4.0),
    )
    oof = np.zeros(len(y))
    for tr_idx, val_idx in skf3.split(X_arr, y):
        m = LGBMClassifier(**params, n_jobs=4, random_state=42, verbose=-1)
        m.fit(X_arr[tr_idx], y[tr_idx])
        oof[val_idx] = m.predict_proba(X_arr[val_idx])[:, 1]

    # Find best F2 threshold for this set of params
    best = max(
        fbeta_score(y, (oof >= t).astype(int),
                    beta=2, average="binary", zero_division=0)
        for t in np.arange(0.05, 0.9, 0.01)
    )
    return best

# Run Optuna (50 trials ≈ 10-15 min on this dataset)
study = optuna.create_study(direction="maximize", sampler=TPESampler(seed=42))
study.optimize(objective, n_trials=50, show_progress_bar=True)

print(f"\n🏆 Best F2 (3-fold CV): {study.best_value:.5f}")
print(f"   Best params: {study.best_params}")

# -------------------------------------------------
# 4️⃣  Retrain best model on full data with 5-fold OOF
# -------------------------------------------------
best_params = study.best_params
skf5 = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
oof5 = np.zeros(len(y))
models_final = []

for fold, (tr_idx, val_idx) in enumerate(skf5.split(X_arr, y)):
    m = LGBMClassifier(**best_params, n_jobs=4, random_state=42, verbose=-1)
    m.fit(X_arr[tr_idx], y[tr_idx])
    oof5[val_idx] = m.predict_proba(X_arr[val_idx])[:, 1]
    models_final.append(m)
    print(f"  Fold {fold+1} done")

# Find final threshold on 5-fold OOF
best_thr, best_f2 = 0.5, 0.0
for thr in np.arange(0.05, 0.9, 0.005):
    f2 = fbeta_score(y, (oof5 >= thr).astype(int),
                     beta=2, average="binary", zero_division=0)
    if f2 > best_f2:
        best_f2, best_thr = f2, thr

print(f"\n🔎 Optimal threshold → {best_thr:.3f}")
print(f"📈 Final OOF F2      → {best_f2:.5f}  (target ≥ 0.70)")

# -------------------------------------------------
# 5️⃣  Predict on test & save submission
# -------------------------------------------------
test_raw = pd.read_csv("test.csv")
test_ids = test_raw["ID"]
test_df  = engineer(preprocess(test_raw.drop(columns=["ID"]), keep_columns=None))
test_df  = test_df.reindex(columns=train_cols, fill_value=0)

proba_test = np.mean([m.predict_proba(test_df.values)[:, 1] for m in models_final], axis=0)
test_pred  = (proba_test >= best_thr).astype(int)

submission = pd.DataFrame({
    "ID": test_ids,
    "History of HeartDisease or Attack": test_pred
})
submission["History of HeartDisease or Attack"] = submission["History of HeartDisease or Attack"].replace({1:"Yes", 0:"No"})
submission.to_csv("submission.csv", index=False)

print(f"\n🚀 Submission saved!")
print(submission["History of HeartDisease or Attack"].value_counts())

✅ Training shape: (221390, 37) | pos_weight: 11.3

Best trial: 17. Best value: 0.544151: 100%|██████████| 50/50 [20:20<00:00, 24.41s/it]

🏆 Best F2 (3-fold CV): 0.54415
   Best params: {'n_estimators': 642, 'learning_rate': 0.021611356499436477, 'num_leaves': 113, 'max_depth': 4, 'min_child_samples': 32, 'subsample': 0.5074211794572681, 'colsample_bytree': 0.5087744508350031, 'reg_alpha': 0.0077558475829739145, 'reg_lambda': 1.389327816577002, 'scale_pos_weight': 30.250951421322515}
  Fold 1 done
  Fold 2 done
  Fold 3 done
  Fold 4 done
  Fold 5 done

🔎 Optimal threshold → 0.775
📈 Final OOF F2      → 0.54386  (target ≥ 0.70)

🚀 Submission saved!
History of HeartDisease or Attack
No     51963
Yes    22398
Name: count, dtype: int64